services:
  foodie-backend:
    build:
      context: .
      dockerfile: foodie-connect-backend.api/Dockerfile
    depends_on:
      - postgres
  
  postgres:
    image: postgis/postgis:17-3.5
    container_name: foodie-postgres
    volumes:
        - foodie-data:/var/lib/postgresql/data 
     
volumes:
  foodie-data:
  foodie-cache: